### ISSUE TITLE
Files marked as "[ DELETE ]" aren't being deleted

### ISSUE THREAD

**Issue by AndersonTorres** [atgreen/paperless#14]
Hello, people!

I was using paperless yesterday, and I find that small bug: it refused to "move to trash" the files marked for deletion

Maybe this is because of these two lines here:

https://github.com/atgreen/paperless/blob/b3b6c05da393f6b1292a3d5937bc4499baabd0b6/paperless.el#L109

https://github.com/atgreen/paperless/blob/b3b6c05da393f6b1292a3d5937bc4499baabd0b6/paperless.el#L152

**Comment by atgreen** [comment]
Thank you for this!  I've fixed it.
