### ISSUE TITLE
idea : expand to other file format and add tags

### ISSUE THREAD

**Issue by DriXse** [atgreen/paperless#4]
Hi,
Thx for this tools, it's a great idea, i use dired with tags from bookmark+, i think your tools can replace my workflow to organize documents.

can you think it is possible to expand to other file format like odt, jpg, etc ? and add tag ? then it can be to have less of directory and sub directory and more possibility of categorization and search ? 

thx.

**Comment by atgreen** [comment]
Thanks for the feedback @DriXse .  I'm not familiar with bookmark+ or tags.  Can you explain how this might work with paperless?

I think supporting different file types should be easy.  Perhaps I should add a customize variable listing the supported file extensions.  I don't know how we could preview odt files, though.

**Comment by nashamri** [comment]
Previewing JPGs and PNGs would be nice to have. In my case, I use my phone to scan documents using the Dropbox app and then export the scans as JPGs and PDFs.

**Comment by atgreen** [comment]
That's a great idea.  I'll look into it.

Thanks,

AG
